### ISSUE TITLE
Vector Too Long

### ISSUE THREAD

**Issue by iamslamjr** [zhuowei/WDBRemoveThreeAppLimit#10]
Trying To Install On AltStore, Using New Beta That Fixed The Provision Error, And Im Getting An Error That Says “vector too long”

**Comment by MelonLoader** [comment]
My issue was it being blocked my AV allowing it fixed it for me during JIT mode

**Comment by iamslamjr** [comment]
> 

I figured it out, my real time protection was on, on my pc, disabled it, and it fixed the problem.
