### ISSUE TITLE
How to sign new ipa after installing

### ISSUE THREAD

**Issue by githubashutoshsoni** [zhuowei/WDBRemoveThreeAppLimit#2]
I installed using altserver. Pressed okay. Everything working. Then I went to altserver to install new ipa it said I can’t install due to 3 app limit. Can you tell me how you achieved this? Thanks!

**Comment by TheCountOfCash** [comment]
Same error

**Comment by bisco904** [comment]
same issue here. thank you for all your hard work!

**Comment by jxjot** [comment]
> I installed using altserver. Pressed okay. Everything working. Then I went to altserver to install new ipa it said I can’t install due to 3 app limit. Can you tell me how you achieved this? Thanks!

open the removeapplimit app on the phone and sideloadly on computer. click start on sideloadly, and as soon as you see "uploading" status on sideloadly, you gotta tap "go" on removeapplimit app. 

you gotta close the removeapplimit app completely after you install the previous ipa. you should only see "go" on the removeapplimit, not "success, go" before you install the next ipa.

**Comment by githubashutoshsoni** [comment]
i saw the uploading status and then pressed go. but the app crashed after that. and the same error popped up. I tried multiple times still the same issue keeps happening. i'm on iOS 16.0.2. Can you make a video of it or update the readme so It's clearer?

**Comment by githubashutoshsoni** [comment]
i saw the uploading status and then pressed go. but the app crashed after that. and the same error popped up. I tried multiple times still the same issue keeps happening. i'm on iOS 16.0.2. Can you make a video of it or update the readme so It's clearer?

**Comment by githubashutoshsoni** [comment]
Okay! I got it working by installing altsotre, uyouplus and filizaescaped and wdb remove 3 app limit. So 4 apps I have right now. Cool. I think the new iPas that I have must be problem with the ipa I’ll test with some more ipa files and update you on this.

**Comment by githubashutoshsoni** [comment]
Can you let me know if I have 0 app ids remaining even then I can use this method to install more ipa files? Thanks

**Comment by caoyongit** [comment]
We can wait for the official version of AltStore1.6.1.
[https://twitter.com/altstoreio/status/1623774524352102404](https://twitter.com/altstoreio/status/1623774524352102404)
<img width="627" alt="圖片" src="https://user-images.githubusercontent.com/7878291/218238005-e1690641-f31f-45ba-bc7b-00a4f6554d1f.png">

**Comment by ashutoshbitcot** [comment]
Yes, let’s wait.

**Comment by oldman20** [comment]
> We can wait for the official version of AltStore1.6.1.
> https://twitter.com/altstoreio/status/1623774524352102404
> <img alt="圖片" width="627" src="https://user-images.githubusercontent.com/7878291/218238005-e1690641-f31f-45ba-bc7b-00a4f6554d1f.png">

Seem to long :(

**Comment by matianhe3** [comment]
> Okay! I got it working by installing altsotre, uyouplus and filizaescaped and wdb remove 3 app limit. So 4 apps I have right now. Cool. I think the new iPas that I have must be problem with the ipa I’ll test with some more ipa files and update you on this.

how to install?  my remove app show success,  but still more than three.
![image](https://user-images.githubusercontent.com/24929062/219659683-737c84c6-6a3c-46cd-a7ba-49766fbc8d73.png)

![image](https://user-images.githubusercontent.com/24929062/219659760-fd99cd2e-3ff4-497d-b4b4-7d26e1d1e7fe.png)

**Comment by caoyongit** [comment]
> > We can wait for the official version of AltStore1.6.1.
> > https://twitter.com/altstoreio/status/1623774524352102404
> > <img alt="圖片" width="627" src="https://user-images.githubusercontent.com/7878291/218238005-e1690641-f31f-45ba-bc7b-00a4f6554d1f.png">
> 
> Seem to long :(

Sorry,I updated to AltStore1.6.1 today, same error!

**Comment by caoyongit** [comment]
You can refer to this video,https://www.youtube.com/watch?v=5DO-P32g7W8&t=75s . 
important“The 3 finger swipe shows the debug stuff”.
My altserver.app is also 1.6.1 and I did it!
Try several times and restart your phone or computer.

**Comment by ravne111** [comment]
iPhone 12 mini, iOS 16.2, im having this error trying to sideload 4th app.
![IMG_0087](https://user-images.githubusercontent.com/22574876/220398185-a205f7f1-fc4d-40ec-bee9-f398fd200052.PNG)

**Comment by ImaSimp-MrYumYum** [comment]
> iPhone 12 mini, iOS 16.2, im having this error trying to sideload 4th app. ![IMG_0087](https://user-images.githubusercontent.com/22574876/220398185-a205f7f1-fc4d-40ec-bee9-f398fd200052.PNG)

Got the same error with an Iphone 14 Pro on Ios 16.2

**Comment by anakBAIK00** [comment]
Its not working bro, because your ios not supported. Maximal support ios 16.1.2![image](https://user-images.githubusercontent.com/125390360/220477993-db8f9ca0-930b-451d-a5f5-aa157412011a.jpeg)

**Comment by ImaSimp-MrYumYum** [comment]
Oh, thank you

**Comment by matianhe3** [comment]
works for 12pro ios16.1.2  altstore 1.6.1

**Comment by ImaSimp-MrYumYum** [comment]
Do I have to install the ipa on AltStore or is it an inbuilt feature?

**Comment by gugulumasiro** [comment]
restart your phone after deviating the 3 app limit and use an ipa file to sideload, not the "activate".

**Comment by gugulumasiro** [comment]
restart your phone after disable the 3 app limit and use an ipa file to sideload, not the "activate".

**Comment by gugulumasiro** [comment]
1. restart your phone after disable the 3 app limit.
2. use an ipa file to sideload, not the "activate".

**Comment by gugulumasiro** [comment]
restart your phone after the 3 app limit has been disabled if it doesn't work at the first time.

**Comment by duckcantcode** [comment]
> You can refer to this video,https://www.youtube.com/watch?v=5DO-P32g7W8&t=75s . important“The 3 finger swipe shows the debug stuff”. My altserver.app is also 1.6.1 and I did it! Try several times and restart your phone or computer.

this fixed it for me. as long as you are on the correct iOS and you have altstore 1.6.1, you can do the three finger swipe, switch off "enforce 3-app limit", and you're golden. WDBRemoveThreeAppLimit is amazing.
