### ISSUE TITLE
Detected virus on windows

### ISSUE THREAD

**Issue by mizzimizzu** [zhuowei/WDBRemoveThreeAppLimit#30]
![image](https://github.com/zhuowei/WDBRemoveThreeAppLimit/assets/155788720/b2f0ead6-1729-4742-9346-43d0594bf222)
![Screenshot 2024-06-14 221649](https://github.com/zhuowei/WDBRemoveThreeAppLimit/assets/155788720/64ce1c78-acaf-482b-ba42-aa1af13c7e6e)

**Comment by Sieg38** [comment]
Hello, I received an email from you telling me that the PC was infected with a virus. Can you tell me more please thank youBien à vous Siegfried charpentier Le 15 juin 2024 à 04:18, MIZZMIZZU!! ***@***.***> a écrit :﻿
image.png (view on web)
Screenshot.2024-06-14.221649.png (view on web)

**Comment by mizzimizzu** [comment]
what the hell
